[AMQ-9296] Add support of credentials to the docker image
apache/activemq pull request #1050
Opened 2023-09-08 07:38 UTC by essobedo

Fixes https://issues.apache.org/jira/browse/AMQ-9296

## Motivation

Since Docker images for Apache ActiveMQ are published, it would be great to support env vars for USER and PASSWORD.

## Modifications:

* Add an entry point script to generate the configuration files if the environment variable `ACTIVEMQ_USER` is set
* Describe the supported environment variables

2023-10-15 06:08 UTC, jbonofre requested changes
I'm not sure adding an authenication plugin is what's expected.
IMHO, the user (in Jira) is asking for authentication on the webconsole, so updating `jetty-realm.properties`.  The same can apply to `credentials.properties` and `users.properties`. I can explain to you the use of those different files.
So I think, we could have different env variables, depending the credentials we want to set.

2023-10-16 08:17 UTC, essobedo commented
I understand the differences with the authentication on the web console, I simply believed that it is what the OP was expecting. I guess the OP needs to clarify a bit more because it is really unclear/misleading

2023-10-16 08:40 UTC, jbonofre commented
Agree, the ticket should provide some details. However, I think it would be acceptable to have different env variables, depending what kind of credentials we want to provide.

2023-11-10 14:14 UTC, jbonofre commented
Superseded by #1114 1114

2023-11-10 14:14 UTC, closed without merging