[AMQ-8316] Remove unused methods in BrokerService
apache/activemq pull request #988
Opened 2023-03-13 13:08 UTC by jbonofre

2023-03-13 21:31 UTC, cshannon requested changes
I talked to @jbonofre offline and because this change could break existing users that reference the setters/getters in code or set the value in their config the plan will be to keep the these properties and getters/setters in 5.18.0 but mark them as deprecated using `@Deprecated(forRemoval = true)` (along with a note with the release notes for users). Then they can be removed entirely for 5.19.0. This way we can communicate with 5.18.0 release that users need to fix their config.

2023-03-14 09:58 UTC, jbonofre commented
@cshannon can you please take a look ? Thanks !

2023-03-14 10:07 UTC, cshannon requested changes
Deprecation looks good but we should use the @deprecated javadoc flag

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: it will be removed as it should not be used directly.
```suggestion
     * @deprecated it will be removed as it should not be used directly.
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:07 UTC, cshannon commented on activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
> +     * Deprecated: this method will be renamed to not use slave wording
```suggestion
     * @deprecated this method will be renamed to not use slave wording
```

2023-03-14 10:17 UTC, cshannon approved these changes
LGTM, just make sure to verify the commit message when you squash and merge but should be good to go

2023-03-14 11:07 UTC, merged